#!/bin/bash

#################################################################
: <<'Title'
  ____        ____   _                           _               
 / ___| ___  / ___| | |    __ _ _   _ _ __   ___| |__   ___ _ __ 
| |  _ / _ \| |  _  | |   / _` | | | | '_ \ / __| '_ \ / _ \ '__|
| |_| | (_) | |_| | | |__| (_| | |_| | | | | (__| | | |  __/ |   
 \____|\___/ \____| |_____\__,_|\__,_|_| |_|\___|_| |_|\___|_|   
                                                                 
Title
#################################################################

clear
games=( 'bald1' 'bald2' 'deadcells' 'dungeons2' 'gungeon' 'icon' 'neverwinter' 'stardew' )

echo "---Options---"
for element in "${games[@]}"
do
    echo ": $element"
done
echo "-------------"

read -p "Game: " game
lower=${game,,}

case $lower in
    bald1)
        /home/ari/GOG\ Games/Baldurs\ Gate\ Enhanced\ Edition/start.sh
        ;;
    bald2)
        /home/ari/GOG\ Games/Baldurs\ Gate\ 2\ Enhanced\ Edition/start.sh
        ;;
    deadcells)
        /home/ari/GOG\ Games/Dead\ Cells/start.sh
        ;;
    dungeons2)
        /home/ari/GOG\ Games/Dungeons\ 2/start.sh
        ;;
    gungeon)
        /home/ari/GOG\ Games/Enter\ the\ Gungeon/start.sh
        ;;
    icon)
        /home/ari/GOG\ Games/Iconoclasts/start.sh
        ;;
    neverwinter)
        /home/ari/GOG\ Games/Neverwinter\ Nights\ Enhanced\ Edition/start.sh
        ;;
    stardew)
        /home/ari/GOG\ Games/Stardew\ Valley/start.sh
        ;;
    *)
        echo "failed input error"
        ;;
esac
