#!/bin/bash
#GoG Game Launcher version 3.7
#################################################################
: <<'Banner'
  ____        ____   _                           _               
 / ___| ___  / ___| | |    __ _ _   _ _ __   ___| |__   ___ _ __ 
| |  _ / _ \| |  _  | |   / _` | | | | '_ \ / __| '_ \ / _ \ '__|
| |_| | (_) | |_| | | |__| (_| | |_| | | | | (__| | | |  __/ |   
 \____|\___/ \____| |_____\__,_|\__,_|_| |_|\___|_| |_|\___|_|   
                                                                 
Banner
#################################################################

#Functions used in the script
redo() {
	for i in `seq 1 5`; do
    	sleep .1
    	echo -n "."
	done
	kill $0 2> /dev/null
	exec $0
}
function ctrl_z() {
	echo
	echo "ERROR: SIGTSTP(ctrl_z) NOT SUPPORTED"
	echo "ERROR RESTARTING"
	redo
}

#trap section : stops script from being able to sleep
trap ctrl_z sigtstp

games=(/home/ari/GOG\ Games/*)
number=0

clear

#Prints out all options that appear in the array
echo "---Options---"
for element in "${games[@]}"
do
    echo ": $number ${element:20}"
	number=$((number+1))
done
echo "-------------"

read -p "Choice: " choice

if [ $choice -gt $number 2> /dev/null ] || [ $choice -lt 0 2> /dev/null ]
then
	echo "Input Error : Choice Not Listed : Restarting"
	redo
elif [ $choice -eq $choice 2> /dev/null ]
then
	exec "${games[$choice]}/start.sh"
else
	echo "Input Error : Restarting Script"
	redo
fi
