#!/bin/bash
#GoG Game Launcher version 4.2 - Author:Arisena
#################################################################
: <<'Banner'
  ____        ____   _                           _ 
 / ___| ___  / ___| | |    __ _ _   _ _ __   ___| |__   ___ _ __ 
| |  _ / _ \| |  _  | |   / _` | | | | '_ \ / __| '_ \ / _ \ '__|
| |_| | (_) | |_| | | |__| (_| | |_| | | | | (__| | | |  __/ |   
 \____|\___/ \____| |_____\__,_|\__,_|_| |_|\___|_| |_|\___|_|   
                                                                 
Banner
#################################################################

#Variables, makes an array with all games in that directory, needs changed if installing games outside home directory
games=(/mnt/alt-drive/GoG\ Games/*)
number=0

#Create a log file and clear it each time the script starts
log="/tmp/gog-launcher.log"
if [ -f "$log" ];
then
    echo "" > "$log"
fi

#Append output to the log file
exec {out}>"$log"
date_time=$( date '+%D::%H:%M' )
echo "Log Start $date_time" > $log

clear

#Prints out all options that appear in the array
echo "Username=$USER ; Please verify mount points in script"
echo "          ---Options---"
for element in "${games[@]}"
do
    echo ": $number ${element:25}"
	number=$((number+1))
done
echo "          -------------"
echo "'exit' is also valid"

read -p "Choice: " choice

#Check if the user input a number, if not, restart
if [ $choice -eq $((number)) ]
then
	echo "Input Error"
    exit 1
elif grep -q exit <<<"$choice";
then
	exit 0
fi

#Checks if the choice exists in the array
if [ $choice -gt $number ] || [ $choice -lt 0 ] || [ -z "$choice" ]
then
	echo "Input Error : Choice Not Listed : Restarting"
	sleep .5
    exit 1
elif [ $choice -eq $choice ]
then
    clear
    echo "Executing game..."
    echo "Log file at : $log"
	exec "${games[$choice]}/start.sh" | tee >>"$log"
else
	echo "Input Error : Restarting Script"
	sleep .5
    exit 1
fi
