#!/bin/bash
#GoG Game Launcher version 4.0 - Author:Arisena
#################################################################
: <<'Banner'
  ____        ____   _                           _ 
 / ___| ___  / ___| | |    __ _ _   _ _ __   ___| |__   ___ _ __ 
| |  _ / _ \| |  _  | |   / _` | | | | '_ \ / __| '_ \ / _ \ '__|
| |_| | (_) | |_| | | |__| (_| | |_| | | | | (__| | | |  __/ |   
 \____|\___/ \____| |_____\__,_|\__,_|_| |_|\___|_| |_|\___|_|   
                                                                 
Banner
#################################################################

#Source file for functions used in the script
source /usr/local/lib/Trap.sh

games=(/home/ari/GOG\ Games/*)
number=0
sstop=exit

clear

#Prints out all options that appear in the array
echo "          ---Options---"
for element in "${games[@]}"
do
    echo ": $number ${element:20}"
	number=$((number+1))
done
echo "          -------------"

read -p "Choice: " choice

if [ $choice -eq $((number)) 2> /dev/null ]
then
	echo "Input Error"
	redo
elif grep -q exit <<<"$choice";
then
	exit 0
fi

if [ $choice -gt $number 2> /dev/null ] || [ $choice -lt 0 2> /dev/null ] || [ -z "$choice" ]
then
	echo "Input Error : Choice Not Listed : Restarting"
	sleep .5
	redo
elif [ $choice -eq $choice 2> /dev/null ]
then
	exec "${games[$choice]}/start.sh"
else
	echo "Input Error : Restarting Script"
	sleep .5
	redo
fi
