#!/bin/bash
#GoG Game Launcher GUI Edition
games=(/mnt/alt-drive/GOG\ Games/*)
name=("${games[@]##*/}")
number=0

choice=$(zenity --width 500 --height 500 --list --column "Games Installed, please verify mount point in script" "${name[@]}")

echo $choice

if [ -z $choice ]
then
    exit 1
else
    exec "~/GOG Games/$choice/start.sh"
fi
