#!/bin/bash
#GoG Game Launcher GUI Edition
games=(/home/*/GOG\ Games/*)
name=("${games[@]##*/}")
number=0

choice=$(zenity --width 500 --height 500 --list --column "Games Installed, they must be in your Home Directory" "${name[@]}")

echo $choice

if [ -z $choice ]
then
    exit 1
else
    exec "~/GOG Games/$choice/start.sh"
fi
