#!/bin/bash
#GoG Game Launcher GUI Edition
games=(/home/*/GOG\ Games/*)
name=("${games[@]##*/}")
number=0

choice=$(zenity --width 500 --height 500 --list --column "Name" "${name[@]}")

echo $choice

exec "GOG Games/$choice/start.sh"
