#!/bin/bash
#GoG Game Launcher version 3.7
#################################################################
: <<'Banner'
  ____        ____   _                           _ 
 / ___| ___  / ___| | |    __ _ _   _ _ __   ___| |__   ___ _ __ 
| |  _ / _ \| |  _  | |   / _` | | | | '_ \ / __| '_ \ / _ \ '__|
| |_| | (_) | |_| | | |__| (_| | |_| | | | | (__| | | |  __/ |   
 \____|\___/ \____| |_____\__,_|\__,_|_| |_|\___|_| |_|\___|_|   
                                                                 
Banner
#################################################################

#Functions used in the script
redo() {
	for i in `seq 1 5`; do
    	sleep .1
    	echo -n "."
	done
	kill $0 2> /dev/null
	exec $0
}
function ctrl_z() {
	echo
	echo "ERROR: SIGTSTP(ctrl_z) NOT SUPPORTED"
	echo "ERROR RESTARTING"
	redo
}

#trap section : stops script from being able to sleep
trap ctrl_z sigtstp
games=(/home/ari/GOG\ Games/*)

exec 3>&1
selection=$(dialog --title "Graphical Interface" \
	--backtitle 'WIP' \
	--clear \
	--cancel-label 'Exit' \
	--menu "Please Select:" 11 30 4 \
	"1" "Baldurs Gate 1" \
	"2" "Baldurs Gate 2" \
	"3" "Dead Cells" \
	"4" "Dungeons 2" \
	"5" "Enter the Gungeon" \
	"6" "Iconoclasts" \
	"7" "Neverwinter Nights" \
	"8" "Stardew Valley" \
	2>&1 1>&3)

case $selection in
	1)
		exec "/home/ari/GOG Games/Baldurs Gate Enhanced Edition/start.sh"
		;;
	2)
		exec "/home/ari/GOG Games/Baldurs Gate 2 Enhanced Edition/start.sh"
		;;
	3)
		exec "/home/ari/GOG Games/Dead Cells/start.sh"
		;;
	4)
		exec "/home/ari/GOG Games/Dungeons 2/start.sh"
		;;
	5)
		exec "/home/ari/GOG Games/Enter the Gungeon/start.sh"
		;;
	6)
		exec "/home/ari/GOG Games/Iconoclasts/start.sh"
		;;
	7)
		exec "/home/ari/GOG Games/Neverwinter Nights Enhanced Edition/start.sh"
		;;
	8)
		exec "/home/ari/GOG Games/Stardew Valley/start.sh"
		;;
esac



: <<old
games=(/home/ari/GOG\ Games/*)
number=0

#Prints out all options that appear in the array
echo "          ---Options---"
for element in "${games[@]}"
do
    echo ": $number ${element:20}"
	number=$((number+1))
done
echo "          -------------"

read -p "Choice: " choice

if [ $choice -gt $number 2> /dev/null ] || [ $choice -lt 0 2> /dev/null ]
then
	echo "Input Error : Choice Not Listed : Restarting"
	redo
elif [ $choice -eq $choice 2> /dev/null ]
then
	exec "${games[$choice]}/start.sh"
else
	echo "Input Error : Restarting Script"
	redo
fi
old
